### ISSUE TITLE
File Extraction Question

### ISSUE THREAD

**Issue by yj0524** [TheGreatRambler/MariOver#12]
I searched the internet to extract the `SUPER MARIO MAKER 2 v0 (01009B90006DC000) (BASE).tik` file, but it looks like I'm at risk of getting my device permanently banned. How do I safely extract my files?

**Comment by TheGreatRambler** [comment]
Luckily you do not need to dump your ticket anymore, the only files necessary are:
1. PRODINFO.dec
2. prod.keys
3. System savefile 8000000000000010

**Comment by yj0524** [comment]
Thank you! I have everything.
