### ISSUE TITLE
slow response time

### ISSUE THREAD

**Issue by UltraBlackLinux** [TheGreatRambler/MariOver#3]
Hey there,
I've been trinking about creating a gui for this, but why is your website so slow? Is that intentional, or not? Are you encouraging people to host it themselves?
The current state works, but one level view or download takes several minutes...
Thanks!

**Comment by TheGreatRambler** [comment]
Yeah, the api is highly susceptible to single users hogging it unfortunatelt

**Comment by UltraBlackLinux** [comment]
Add per user rate limit maybe? I've created a script to download random courses, but I had to test it a few times, a rate limit would  make me happy
@TheGreatRambler

**Comment by TheGreatRambler** [comment]
The main issue isn't exactly a rate limit, it's that requests are limited to one person globally at a time, the rate limit is once every 10 seconds for everyone
