### ISSUE TITLE
Server returning 500

### ISSUE THREAD

**Issue by os-lover** [TheGreatRambler/MariOver#4]
Hey there,

I'm using your API to make a python project that checks whether the level you have entered is valid. The problem is, I have an if/else statement that always returns else. The program then reports that the level can't be found. I was confused because the level code was valid in SMM2. So, I checked the status code. Lo and behold, error 500! The weird part of this is that the server works fine on browser albeit a little slow.

I'm quite new to this, so don't go to complicated on me!

Thank you.

Code:

    if response.status_code == 200:
        pleasewait_Label.pack_forget()
        levelfound()
    else:
        cannotfind_Label.pack()
        pleasewait_Label.pack_forget()

**Comment by TheGreatRambler** [comment]
What code is it?

**Comment by os-lover** [comment]
I've tried so many codes, they all don't work. (I forgot to mention the website is fine)

**Comment by TheGreatRambler** [comment]
429 is the new error code for rate limiting, if you receive 500 that is unexpected and should be reported.
